version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.14
        environment:
          NODE_ENV: test
          REQUEST_LOGGING: false
          DB_LOGGING: false
          DB_HOST: 127.0.0.1
          DB_DATABASE: accounts
          DB_USER: accounts
          DB_PASSWORD: password
      - image: circleci/mysql:latest
        command: [--default-authentication-plugin=mysql_native_password]
        environment:
          MYSQL_ROOT_PASSWORD: rootpw
          MYSQL_DATABASE: accounts
          MYSQL_USER: accounts
          MYSQL_PASSWORD: password

    working_directory: ~/account-service/node

    steps:
      - checkout:
          path: ~/account-service

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Waiting for MySQL to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MySQL && exit 1

      - run: npx sequelize-cli db:migrate

      # run tests!
      - run: npm test

