version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.14
        environment:
          NODE_ENV: test
      - image: circleci/mysql:8.0.4
        environment:
          MYSQL_ROOT_PASSWORD: rootpw
          MYSQL_DATABASE: accounts
          MYSQL_USER: accounts
          MYSQL_PASSWORD: password

    working_directory: ~/account-service/node

    steps:
      - checkout:
          path: ~/account-service

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: npm test

